const generated = Object.freeze({
  provider: 'Azure OpenAI',
  model: 'gpt-image-2',
  mode: 'generate',
  generatedAt: '2026-08-16',
});

const fluxGenerated = Object.freeze({
  provider: 'Azure AI Foundry',
  model: 'FLUX.2-pro',
  mode: 'generate + deterministic matte extraction',
  generatedAt: '2026-09-06',
});

const fluxCompositeGenerated = Object.freeze({
  provider: 'Azure AI Foundry + Plundrix compositor',
  model: 'FLUX.2-pro',
  mode: 'generated environment + deterministic reusable-part composition',
  generatedAt: '2026-09-06',
});

const fluxSceneGenerated = Object.freeze({
  provider: 'Azure AI Foundry',
  model: 'FLUX.2-pro',
  mode: 'generate',
  generatedAt: '2026-09-06',
});

const acceptedChecks = Object.freeze([
  'focal subject reads at 240px wide',
  'no text, logo, watermark, fake UI, coins, or treasure',
  'mechanical details match the declared gameplay truth',
  'desktop and mobile crops preserve the focal beat',
]);

function inventoryPart({ id, label, part, role, brief, subject, joy, avoid = [], directives = '' }) {
  const file = id.replace(/^part-/, '');
  return {
    id,
    label,
    family: 'transparent-part',
    status: 'accepted',
    role,
    brief,
    providerDirectives: {
      flux2Pro: `ABSOLUTELY BLANK OBJECT SURFACES. ${directives} No text, letters, numbers, symbols, labels, logo, watermark, screen, gauge, hands, people, face, limbs, weapon, coins, treasure, or scene background.`,
    },
    scene: 'Transparent canvas.',
    subject,
    parts: [part],
    composition: 'One centered collectible object in front three-quarter view, complete silhouette, sturdy contact point, 14 percent transparent padding.',
    lighting: 'Neutral studio key with warm amber edge light and one restrained semantic accent.',
    joy,
    constraints: ['one object only', 'genuinely transparent background', 'readable at 64px', 'blank manufactured surfaces'],
    avoid: ['text', 'letters', 'numbers', 'symbols', 'logo', 'screen', 'gauge', 'hand', 'person', 'face', 'weapon', 'coins', 'treasure', 'scene background', ...avoid],
    source: `assets/art-source/parts/inventory/${file}.png`,
    canvas: { width: 1024, height: 1024 },
    outputs: [{ path: `public/images/inventory/${file}.webp`, publicPath: `/images/inventory/${file}.webp`, width: 512, height: 512, fit: 'contain', format: 'webp', quality: 88, minBytes: 8_000, maxBytes: 180_000, alpha: true }],
    alt: `A ${label.toLowerCase()} component.`,
    generation: fluxGenerated,
    manualChecks: ['transparent corners have zero alpha', 'silhouette reads at 64px', 'contains no writing, face, weapon, or currency cues'],
  };
}

export const ART_ASSETS = Object.freeze([
  {
    id: 'vault-hero',
    label: 'Vault hero',
    family: 'vault-atmosphere',
    status: 'accepted',
    role: 'Brand promise',
    brief: 'Introduce one imposing vault that feels precise, competitive, and possible to crack.',
    scene: 'A clandestine industrial strategy chamber centered on one monumental vault door.',
    subject: 'One vault mechanism surrounded by restrained operator infrastructure.',
    parts: ['vault-monolith', 'operator-station', 'blueprint-trace', 'calm-copy-field'],
    composition: 'Square master with strong central symmetry and calm edge space that survives a wide crop.',
    lighting: 'Warm amber rim light on the vault against cool, near-black chamber shadows.',
    joy: {
      target: 'anticipation',
      mechanism: 'The vault looks formidable but visibly operable, inviting the first choice.',
      restraint: 'No breach yet; keep the promise unresolved.',
    },
    constraints: ['one uninterrupted vault face', 'no decorative repeated lock modules'],
    avoid: ['multiple competing vault doors', 'horror imagery', 'empty generic sci-fi corridor'],
    source: 'assets/art-source/scenes/plundrix-vault-hero.png',
    canvas: { width: 1024, height: 1024 },
    outputs: [
      { path: 'public/images/plundrix-vault-hero.webp', publicPath: '/images/plundrix-vault-hero.webp', width: 1024, height: 1024, fit: 'cover', format: 'webp', quality: 82, minBytes: 70_000, maxBytes: 180_000 },
    ],
    alt: 'A monumental brass vault door inside a dark industrial strategy chamber.',
    generation: generated,
    manualChecks: acceptedChecks,
  },
  {
    id: 'instant-breach',
    label: 'Instant breach',
    family: 'mode-key-art',
    status: 'accepted',
    role: 'No-wallet mode',
    brief: 'Make solo play against three readable mechanical rivals feel immediate and welcoming.',
    providerDirectives: {
      flux2Pro: 'NONNEGOTIABLE COUNTED LAYOUT: show four empty workstations, all visibly separate: one large foreground player bench plus three smaller matching rival benches in a rear row at left, center, and right. Behind them, show five identical brass lock bolts total in one straight horizontal row. Do not add a central lock, dial, or other lock-like circle. Use levers and hand tools only. Every surface is blank. No writing, labels, symbols, numbers, check marks, monitors, screens, gauges, people, humanoids, robots, heads, torsos, arms, or hands.',
    },
    composite: {
      basePrompt: 'Create a square 1024x1024 text-free cinematic game environment base for a premium industrial vault strategy game. COMPOSITE BASE ONLY: show exactly four empty workstations, all separate: one large player workbench across the lower foreground and exactly three smaller plain mechanical rival benches in the middle distance at left, center, and right. Behind them is one wide, completely blank, flat blackened-steel vault panel occupying the upper-right half, intentionally empty for five lock modules that will be composited later. The blank vault panel must contain zero locks, zero circles, zero holes, zero dials, zero gauges, and zero decorations. Each workstation uses only simple unlabeled levers and a few precision hand tools. No screens, monitors, digital displays, gauges, keyboards, chairs, writing, letters, numbers, labels, symbols, logos, watermarks, borders, people, robots, body parts, or faces. Premium painterly 3D game art, physically grounded blackened steel, aged brass, worn enamel, warm amber task light against cool near-black shadows. Preserve calm dark low-detail negative space in the upper-left for later HTML copy. Competitive and welcoming, not menacing. Image only.',
      part: 'assets/art-source/parts/lock-module.png',
      expectedCount: 5,
      size: 104,
      positions: [[420, 214], [530, 214], [640, 214], [750, 214], [860, 214]],
      clones: [
        { from: [510, 616, 70, 68], to: [440, 616] },
        { from: [820, 616, 70, 68], to: [750, 616] },
      ],
    },
    scene: 'A compact clandestine training vault shared by one foreground workbench and three rival stations.',
    subject: 'EXACT COUNTS: four empty workstations total - one foreground player bench and exactly three smaller unoccupied rival consoles - facing exactly five lock cylinders total on the vault face.',
    parts: ['five-lock-rack', 'operator-station', 'mechanical-rival', 'calm-copy-field'],
    composition: 'Square card art weighted right and low with a calm dark upper-left copy field.',
    lighting: 'Warm approachable vault light with subtle cool separation between the three rivals.',
    joy: {
      target: 'invitation',
      mechanism: 'The waiting rival stations make the table feel alive before the first action.',
      restraint: 'Competitive, not menacing; no blockchain imagery.',
    },
    constraints: ['exactly three unoccupied rival consoles', 'exactly one foreground player workbench', 'exactly five visible lock cylinders total', 'all surfaces are free of writing and labels'],
    avoid: ['people', 'humanoid robots', 'heads', 'torsos', 'arms', 'hands', 'screens', 'gauges with letters or numerals', 'extra lock-like circles', 'crowded upper-left detail', 'victory before play begins'],
    source: 'assets/art-source/scenes/plundrix-instant-breach.png',
    canvas: { width: 1024, height: 1024 },
    outputs: [
      { path: 'public/images/plundrix-instant-breach.webp', publicPath: '/images/plundrix-instant-breach.webp', width: 1024, height: 1024, fit: 'cover', format: 'webp', quality: 82, minBytes: 30_000, maxBytes: 180_000 },
    ],
    alt: 'A training vault with one player workbench facing three mechanical rival stations.',
    generation: fluxCompositeGenerated,
    manualChecks: acceptedChecks,
  },
  {
    id: 'live-breach',
    label: 'Live breach',
    family: 'mode-key-art',
    status: 'accepted',
    role: 'Connected mode',
    brief: 'Communicate four connected competitors making simultaneous decisions around one vault.',
    scene: 'A dark metal strategy table with four empty stations connected to one five-lock vault.',
    subject: 'Four grounded operator terminals linked by quiet blueprint circuitry and one sabotage trace.',
    parts: ['five-lock-rack', 'operator-station', 'blueprint-trace', 'sabotage-cable', 'calm-copy-field'],
    composition: 'Square table perspective weighted right and low with calm dark upper-left space.',
    lighting: 'Amber vault glow, restrained blue connection light, and exactly one red sabotage path.',
    joy: {
      target: 'social tension',
      mechanism: 'Every station points toward the same prize while one red path implies betrayal.',
      restraint: 'Connected competition without crypto symbols or fake players.',
    },
    constraints: ['exactly four operator stations', 'exactly one shared vault', 'fine connection paths remain secondary'],
    avoid: ['network-map abstraction', 'human figures', 'multiple red effects'],
    source: 'assets/art-source/scenes/plundrix-live-breach-gpt-image-2.png',
    canvas: { width: 1024, height: 1024 },
    outputs: [
      { path: 'public/images/plundrix-live-breach.webp', publicPath: '/images/plundrix-live-breach.webp', width: 1024, height: 1024, fit: 'cover', format: 'webp', quality: 82, minBytes: 70_000, maxBytes: 180_000 },
    ],
    alt: 'Four linked operator stations surround a five-lock vault on a dark industrial table.',
    generation: generated,
    manualChecks: acceptedChecks,
  },
  {
    id: 'replay-comeback',
    label: 'Comeback',
    family: 'replay-story',
    status: 'accepted',
    role: 'Narrative proof',
    brief: 'Capture the hopeful instant when a trailing player earns one last credible route back into the race.',
    scene: 'A battered operator bench at the vault during a late-round recovery.',
    subject: 'A precision lockpick finding purchase while a previously dark mechanism begins to glow.',
    parts: ['five-lock-rack', 'operator-station', 'pick-tool', 'breach-light'],
    composition: 'Close, square narrative crop with one diagonal from the tool to the responding lock.',
    lighting: 'A small warm comeback spark growing against deep cool pressure.',
    joy: {
      target: 'hope',
      mechanism: 'The tool-to-lock cause is instantly readable and the race still feels undecided.',
      restraint: 'Show renewed possibility, not a guaranteed win.',
    },
    constraints: ['one recovering station', 'one readable lock response'],
    avoid: ['victory pose', 'scoreboard', 'generic triumphant explosion'],
    source: 'assets/art-source/scenes/replay-comeback.png',
    canvas: { width: 1024, height: 1024 },
    outputs: [
      { path: 'public/images/replay-comeback.webp', publicPath: '/images/replay-comeback.webp', width: 1024, height: 1024, fit: 'cover', format: 'webp', quality: 82, minBytes: 90_000, maxBytes: 220_000 },
    ],
    alt: 'A lockpicker makes a late attempt while the vault begins to respond with warm light.',
    generation: generated,
    manualChecks: acceptedChecks,
  },
  {
    id: 'replay-sabotage',
    label: 'Sabotage',
    family: 'replay-story',
    status: 'accepted',
    role: 'Narrative proof',
    brief: 'Show a clever disruption as a specific cause and consequence, not indiscriminate destruction.',
    scene: 'A rival workbench immediately after one precise act of sabotage.',
    subject: 'A stolen tool across one severed cable while its path back to the rival station remains visible.',
    parts: ['operator-station', 'pick-tool', 'sabotage-cable'],
    composition: 'Tight square still life with the cable path leading through the frame.',
    lighting: 'Restrained red spark against warm brass and quiet cool shadows.',
    joy: {
      target: 'mischief',
      mechanism: 'The viewer can understand exactly what was stolen and who was disrupted.',
      restraint: 'One surgical spark; never an explosion.',
    },
    constraints: ['one severed cable', 'one displaced tool', 'damage remains mechanically plausible'],
    avoid: ['fireball', 'weapons', 'anonymous rubble'],
    source: 'assets/art-source/scenes/replay-sabotage.png',
    canvas: { width: 1024, height: 1024 },
    outputs: [
      { path: 'public/images/replay-sabotage.webp', publicPath: '/images/replay-sabotage.webp', width: 1024, height: 1024, fit: 'cover', format: 'webp', quality: 82, minBytes: 90_000, maxBytes: 220_000 },
    ],
    alt: 'A stolen lockpick rests across a severed cable at a rival vault station.',
    generation: generated,
    manualChecks: acceptedChecks,
  },
  {
    id: 'replay-close-finish',
    label: 'Close finish',
    family: 'replay-story',
    status: 'accepted',
    role: 'Narrative proof',
    brief: 'Make simultaneous final-lock pressure feel readable at a glance.',
    scene: 'Four operator stations converge on the last stage of one shared vault.',
    subject: 'Four distinct tool paths arriving at one nearly breached final lock.',
    parts: ['five-lock-rack', 'operator-station', 'pick-tool', 'breach-light'],
    composition: 'Square radial composition with all paths resolving at one central lock.',
    lighting: 'Balanced station accents around a tightly controlled amber final-lock glow.',
    joy: {
      target: 'suspense',
      mechanism: 'Four readable paths arrive together, making the outcome feel genuinely uncertain.',
      restraint: 'Freeze the instant before the winner is known.',
    },
    constraints: ['exactly four station paths', 'one unresolved final lock'],
    avoid: ['declared winner', 'confetti', 'multiple focal locks'],
    source: 'assets/art-source/scenes/replay-close-finish.png',
    canvas: { width: 1024, height: 1024 },
    outputs: [
      { path: 'public/images/replay-close-finish.webp', publicPath: '/images/replay-close-finish.webp', width: 1024, height: 1024, fit: 'cover', format: 'webp', quality: 82, minBytes: 90_000, maxBytes: 220_000 },
    ],
    alt: 'Four operator stations converge on the unresolved final lock of one vault.',
    generation: generated,
    manualChecks: acceptedChecks,
  },
  {
    id: 'social-home',
    label: 'Home social card',
    family: 'social-source',
    status: 'accepted',
    role: 'Brand sharing',
    brief: 'Make the shared vault and simultaneous rivalry legible in a fast-moving social feed.',
    scene: 'The monumental vault chamber seen from the operator table.',
    subject: 'One vault anchor with subtle evidence of multiple competing stations.',
    parts: ['vault-monolith', 'operator-station', 'blueprint-trace', 'calm-copy-field'],
    composition: 'Landscape source with all essential detail in the right 55 percent and a calm left copy field.',
    lighting: 'High-contrast amber vault light with restrained cool circuitry.',
    joy: { target: 'curiosity', mechanism: 'The unopened vault promises a shared decision with visible stakes.', restraint: 'Mystery without visual vagueness.' },
    constraints: ['protect the left copy field', 'single dominant vault'],
    avoid: ['centered detail behind the headline', 'small intricate silhouettes'],
    source: 'assets/social-source/plundrix-home-gpt-image-2.png',
    canvas: { width: 1536, height: 1024 },
    outputs: [
      { path: 'public/images/og/plundrix-home.jpg', publicPath: '/images/og/plundrix-home.jpg', width: 1200, height: 630, fit: 'cover', format: 'jpeg', quality: 92, minBytes: 50_000, maxBytes: 280_000, treatment: 'social-card-v1', copy: { eyebrow: 'PLUNDRIX', headline: ['CRACK THE VAULT.', 'BREAK THE TABLE.'], footer: 'PICK / SEARCH / SABOTAGE' } },
    ],
    alt: 'Plundrix vault chamber with the words Crack the vault. Break the table.',
    generation: generated,
    manualChecks: acceptedChecks,
  },
  {
    id: 'social-play',
    label: 'Instant Play social card',
    family: 'social-source',
    status: 'accepted',
    role: 'Mode sharing',
    brief: 'Promise a ready-to-play agent table with no wallet barrier.',
    scene: 'A waiting training vault with three mechanical rival stations.',
    subject: 'A prepared operator bench facing three distinct mechanical rivals.',
    parts: ['five-lock-rack', 'operator-station', 'mechanical-rival', 'calm-copy-field'],
    composition: 'Landscape source with the table on the right and a protected left copy field.',
    lighting: 'Warm ready-state light with subtle rival separation.',
    joy: { target: 'readiness', mechanism: 'Everything appears set for an immediate first choice.', restraint: 'No implied wallet or chain setup.' },
    constraints: ['exactly three mechanical rivals', 'protect the left copy field'],
    avoid: ['human faces', 'crypto marks', 'empty unprepared table'],
    source: 'assets/social-source/plundrix-play-gpt-image-2.png',
    canvas: { width: 1536, height: 1024 },
    outputs: [
      { path: 'public/images/og/plundrix-play.jpg', publicPath: '/images/og/plundrix-play.jpg', width: 1200, height: 630, fit: 'cover', format: 'jpeg', quality: 92, minBytes: 50_000, maxBytes: 280_000, treatment: 'social-card-v1', copy: { eyebrow: 'INSTANT PLAY', headline: ['YOUR TABLE', 'IS READY.'], footer: 'NO WALLET REQUIRED' } },
    ],
    alt: 'An Instant Play vault table with the words Your table is ready.',
    generation: generated,
    manualChecks: acceptedChecks,
  },
  {
    id: 'social-trailer',
    label: 'Trailer social card',
    family: 'social-source',
    status: 'accepted',
    role: 'Trailer sharing',
    brief: 'Compress the five-lock, four-player promise into one cinematic frame.',
    scene: 'A shared vault table at peak pre-resolution pressure.',
    subject: 'Four operator stations focused on one five-lock vault.',
    parts: ['five-lock-rack', 'operator-station', 'sabotage-cable', 'calm-copy-field'],
    composition: 'Landscape source with the competitive geometry on the right and a protected left copy field.',
    lighting: 'Peak warm lock light with a single controlled sabotage-red accent.',
    joy: { target: 'dramatic anticipation', mechanism: 'All four positions point at the same nearly solved mechanism.', restraint: 'Do not reveal a winner.' },
    constraints: ['exactly four stations', 'exactly five lock stages', 'protect the left copy field'],
    avoid: ['victory celebration', 'baked-in trailer controls', 'extra lock-like circles'],
    source: 'assets/social-source/plundrix-trailer-gpt-image-2.png',
    canvas: { width: 1536, height: 1024 },
    outputs: [
      { path: 'public/images/og/plundrix-trailer.jpg', publicPath: '/images/og/plundrix-trailer.jpg', width: 1200, height: 630, fit: 'cover', format: 'jpeg', quality: 92, minBytes: 50_000, maxBytes: 300_000, treatment: 'social-card-v1', copy: { eyebrow: 'GAMEPLAY TRAILER', headline: ['ONE VAULT.', 'NO SAFE TURN.'], footer: 'FOUR OPERATORS / FIVE LOCKS' } },
    ],
    alt: 'Four stations around one vault with the words One vault. No safe turn.',
    generation: generated,
    manualChecks: acceptedChecks,
  },
  {
    id: 'part-lock-module',
    label: 'Lock module part',
    family: 'transparent-part',
    status: 'accepted',
    role: 'Reusable progression prop',
    brief: 'Create one modular lock stage that can represent calm, pressured, cracked, and breached states through external lighting.',
    providerDirectives: {
      flux2Pro: 'OBJECT REQUIREMENT: one simple mechanical lock plate with a central keyhole and broad completely blank metal surfaces. No display, window, dial, gauge, tick marks, letters, numbers, symbols, engraving, or pseudo-text.',
    },
    scene: 'Transparent canvas.',
    subject: 'One complete radial lock module with a blackened-steel body, brass mechanism, and a simple central keyhole.',
    parts: ['lock-module'],
    composition: 'Single centered object in a consistent three-quarter view with 12 percent transparent padding.',
    lighting: 'Neutral studio key light; no baked-in semantic glow.',
    joy: { target: 'mastery', mechanism: 'Fine mechanical detail makes progress feel tactile.', restraint: 'The base part remains neutral so state color can be applied in the interface.' },
    constraints: ['genuinely transparent background', 'complete silhouette', 'one module only'],
    avoid: ['scene background', 'floating debris', 'numerals', 'colored state lighting'],
    source: 'assets/art-source/parts/lock-module.png',
    canvas: { width: 1024, height: 1024 },
    outputs: [
      { path: 'public/images/parts/lock-module.webp', publicPath: '/images/parts/lock-module.webp', width: 512, height: 512, fit: 'contain', format: 'webp', quality: 88, minBytes: 20_000, maxBytes: 180_000, alpha: true },
    ],
    alt: 'A round blackened-steel lock module with a central keyhole.',
    generation: fluxGenerated,
    manualChecks: ['transparent corners have zero alpha', 'silhouette reads at 96px', 'no state color is baked in'],
  },
  {
    id: 'part-pick-tool',
    label: 'Pick tool part',
    family: 'transparent-part',
    status: 'accepted',
    role: 'Reusable action prop',
    brief: 'Create the canonical Pick tool as a satisfying, mechanically plausible object.',
    scene: 'Transparent canvas.',
    subject: 'One precision brass lockpick with a blackened-steel grip and subtle wear.',
    parts: ['pick-tool'],
    composition: 'Single diagonal object, complete silhouette, consistent three-quarter view, 12 percent transparent padding.',
    lighting: 'Neutral studio key light with a restrained warm edge.',
    joy: { target: 'agency', mechanism: 'The fine tip and worn grip imply skill and repeated use.', restraint: 'No sparks or success state in the neutral part.' },
    constraints: ['genuinely transparent background', 'one tool only', 'complete silhouette'],
    avoid: ['weapon silhouette', 'hand', 'scene dressing', 'glowing magic effect'],
    source: 'assets/art-source/parts/pick-tool.png',
    canvas: { width: 1024, height: 1024 },
    outputs: [
      { path: 'public/images/parts/pick-tool.webp', publicPath: '/images/parts/pick-tool.webp', width: 512, height: 512, fit: 'contain', format: 'webp', quality: 88, minBytes: 12_000, maxBytes: 160_000, alpha: true },
    ],
    alt: 'A worn brass precision lockpick with a black grip.',
    generation: fluxGenerated,
    manualChecks: ['transparent corners have zero alpha', 'tool reads as lockpicking equipment rather than a weapon', 'silhouette reads at 96px'],
  },
  {
    id: 'part-search-kit',
    label: 'Search kit part',
    family: 'transparent-part',
    status: 'accepted',
    role: 'Reusable discovery prop',
    brief: 'Create the canonical Search kit with one visible useful discovery and room for external state effects.',
    scene: 'Transparent canvas.',
    subject: 'One compact opened field kit containing precision tools and one empty fitted compartment.',
    parts: ['search-kit'],
    composition: 'Single centered kit, open at a readable angle, complete silhouette, 12 percent transparent padding.',
    lighting: 'Neutral studio key light; only a faint restrained green reflection.',
    joy: { target: 'discovery', mechanism: 'The fitted compartments suggest the satisfaction of finding exactly the needed tool.', restraint: 'Do not imply a guaranteed powerful reward.' },
    constraints: ['genuinely transparent background', 'single coherent kit', 'complete silhouette'],
    avoid: ['treasure chest', 'coins', 'loot explosion', 'scene background'],
    source: 'assets/art-source/parts/search-kit.png',
    canvas: { width: 1024, height: 1024 },
    outputs: [
      { path: 'public/images/parts/search-kit.webp', publicPath: '/images/parts/search-kit.webp', width: 512, height: 512, fit: 'contain', format: 'webp', quality: 88, minBytes: 20_000, maxBytes: 180_000, alpha: true },
    ],
    alt: 'An open black field kit containing compact precision tools.',
    generation: fluxGenerated,
    manualChecks: ['transparent corners have zero alpha', 'kit reads at 96px', 'object does not resemble a treasure chest'],
  },
  {
    id: 'part-sabotage-cable',
    label: 'Sabotage cable part',
    family: 'transparent-part',
    status: 'accepted',
    role: 'Reusable disruption prop',
    brief: 'Create one modular severed cable that communicates disruption without explosive violence.',
    providerDirectives: {
      flux2Pro: 'OBJECT REQUIREMENT: one severed braided cable with two inert cut ends and visible copper strands. No spark, electric arc, glow, smoke, flame, debris, or other active effect.',
    },
    scene: 'Transparent canvas.',
    subject: 'One short braided industrial cable with a cleanly severed end, copper strands, and a small connector.',
    parts: ['sabotage-cable'],
    composition: 'Single curved object with complete silhouette and 12 percent transparent padding.',
    lighting: 'Neutral studio key light; no baked-in spark so animation can supply state.',
    joy: { target: 'mischief', mechanism: 'The clean cut creates an instantly readable consequence.', restraint: 'No destruction beyond the cable itself.' },
    constraints: ['genuinely transparent background', 'one cable only', 'complete silhouette'],
    avoid: ['electric arc', 'fire', 'explosion', 'scene background'],
    source: 'assets/art-source/parts/sabotage-cable.png',
    canvas: { width: 1024, height: 1024 },
    outputs: [
      { path: 'public/images/parts/sabotage-cable.webp', publicPath: '/images/parts/sabotage-cable.webp', width: 512, height: 512, fit: 'contain', format: 'webp', quality: 88, minBytes: 20_000, maxBytes: 160_000, alpha: true },
    ],
    alt: 'A severed braided cable with inert copper ends.',
    generation: fluxGenerated,
    manualChecks: ['transparent corners have zero alpha', 'cable reads at 96px', 'no spark or state effect is baked in'],
  },
  {
    id: 'victory-breach',
    label: 'Victory breach',
    family: 'outcome-key-art',
    status: 'accepted',
    role: 'Final briefing payoff',
    brief: 'Show the vault opening as earned mechanical release and give the final result a memorable emotional peak.',
    providerDirectives: {
      flux2Pro: 'ABSOLUTELY TEXT FREE. SCENE REQUIREMENT: an extreme cinematic close-up of one opened vault-door seam releasing warm light. The tight crop must keep the overall lock ring, all bolts, and every numbered mechanism completely outside the frame. Use broad blank blackened-steel surfaces with no diagrams, calibration marks, writing, glyphs, numbers, formulas, signage, logos, watermarks, screens, or interface shapes anywhere. No coins, treasure, gems, cash, people, confetti, explosion, or debris.',
    },
    scene: 'The same clandestine blackened-steel vault chamber immediately after a successful breach.',
    subject: 'A tight macro view of one opened vault seam with controlled warm light beyond it; the overall lock count is deliberately outside the frame.',
    parts: ['vault-monolith', 'breach-light', 'calm-copy-field'],
    composition: 'Square master with the glowing open seam weighted right, low-detail shadow through the center, and no complete locking ring visible in a shallow 1024x420 crop.',
    lighting: 'Warm light escapes through the open seam into cool near-black shadows; restrained dust motes only.',
    joy: { target: 'earned release', mechanism: 'A precise mechanical opening pays off the tension of every earlier choice.', restraint: 'Quiet triumph without loot, fireworks, or a fabricated crowd.' },
    constraints: ['one open vault seam only', 'overall bolt count remains outside the frame', 'center remains calm enough for live winner copy'],
    avoid: ['coins', 'treasure', 'cash', 'people', 'confetti', 'explosion', 'text', 'fake interface'],
    source: 'assets/art-source/scenes/victory-breach.png',
    canvas: { width: 1024, height: 1024 },
    outputs: [
      { path: 'public/images/victory-breach.webp', publicPath: '/images/victory-breach.webp', width: 1024, height: 420, fit: 'cover', format: 'webp', quality: 84, minBytes: 15_000, maxBytes: 180_000 },
    ],
    alt: 'An opened mechanical vault releasing warm light.',
    generation: fluxSceneGenerated,
    manualChecks: ['opened vault seam reads in the 1024x420 crop without presenting a conflicting lock count', 'no text, treasure, explosion, or people', 'warm release supports rather than obscures live result text'],
  },
  {
    id: 'part-precision-kit',
    label: 'Precision Kit gadget',
    family: 'transparent-part',
    status: 'accepted',
    role: 'Tactical Pick gadget',
    brief: 'Create the canonical Precision Kit as a compact collectible equipment module.',
    scene: 'Transparent canvas.',
    subject: 'One fitted blackened-steel tool tray containing exactly three fine brass lock tools and one tension collar.',
    parts: ['precision-kit'],
    composition: 'Single centered kit in three-quarter view with a complete silhouette and 12 percent transparent padding.',
    lighting: 'Neutral studio light with a restrained amber edge.',
    joy: { target: 'prepared confidence', mechanism: 'Ordered, purpose-built tools make the next Pick feel skillful.', restraint: 'No hands, weapons, sparks, or success state.' },
    constraints: ['one coherent kit', 'exactly three fine tools', 'genuinely transparent background'],
    avoid: ['text', 'numbers', 'logos', 'treasure chest', 'hand', 'weapon', 'scene background'],
    source: 'assets/art-source/parts/precision-kit.png',
    canvas: { width: 1024, height: 1024 },
    outputs: [{ path: 'public/images/parts/precision-kit.webp', publicPath: '/images/parts/precision-kit.webp', width: 512, height: 512, fit: 'contain', format: 'webp', quality: 88, minBytes: 12_000, maxBytes: 180_000, alpha: true }],
    alt: 'A compact fitted precision lock-tool kit.',
    generation: fluxGenerated,
    manualChecks: ['transparent corners have zero alpha', 'reads as precision equipment at 72px', 'contains no writing or weapon silhouette'],
  },
  {
    id: 'part-signal-scanner',
    label: 'Signal Scanner gadget',
    family: 'transparent-part',
    status: 'accepted',
    role: 'Tactical Search gadget',
    brief: 'Create the canonical Signal Scanner as a compact analog discovery instrument.',
    providerDirectives: { flux2Pro: 'ABSOLUTELY BLANK OBJECT SURFACES. OBJECT REQUIREMENT: one compact sensor shaped as a simple brass horseshoe around one domed green glass lens, with one short physical antenna and two plain side knobs. Do not include a front panel. No screen, gauge, waveform, tick marks, text, letters, numbers, symbols, labels, logo, or pseudo-text.' },
    scene: 'Transparent canvas.',
    subject: 'One handheld-sized blackened-steel signal scanner with an aged brass frame and a single green glass lens.',
    parts: ['signal-scanner'],
    composition: 'Single centered object in three-quarter view with a complete silhouette and 12 percent transparent padding.',
    lighting: 'Neutral studio light with a faint green lens reflection.',
    joy: { target: 'curiosity', mechanism: 'The one luminous lens suggests a hidden signal waiting to be found.', restraint: 'No digital UI or guaranteed reward.' },
    constraints: ['one scanner only', 'one green lens only', 'genuinely transparent background'],
    avoid: ['screen', 'gauge', 'waveform', 'text', 'numbers', 'hand', 'scene background'],
    source: 'assets/art-source/parts/signal-scanner.png',
    canvas: { width: 1024, height: 1024 },
    outputs: [{ path: 'public/images/parts/signal-scanner.webp', publicPath: '/images/parts/signal-scanner.webp', width: 512, height: 512, fit: 'contain', format: 'webp', quality: 88, minBytes: 12_000, maxBytes: 180_000, alpha: true }],
    alt: 'A compact analog scanner with one green glass lens.',
    generation: fluxGenerated,
    manualChecks: ['transparent corners have zero alpha', 'one lens reads at 72px', 'no screen, gauge, writing, or pseudo-text'],
  },
  {
    id: 'part-firewall',
    label: 'Firewall gadget',
    family: 'transparent-part',
    status: 'accepted',
    role: 'Tactical defense gadget',
    brief: 'Create the canonical Firewall as a sturdy physical relay that can absorb one disruption.',
    providerDirectives: { flux2Pro: 'OBJECT REQUIREMENT: one compact defensive mechanical relay with layered rectangular shutters and copper heat fins. It is equipment, not a heraldic shield. No flame, wall, screen, writing, letters, numbers, symbols, logos, or pseudo-text.' },
    scene: 'Transparent canvas.',
    subject: 'One dense blackened-steel relay with overlapping shutters, sturdy feet, and oxidized copper heat fins.',
    parts: ['firewall-unit'],
    composition: 'Single centered object in three-quarter view with a complete silhouette and 12 percent transparent padding.',
    lighting: 'Neutral studio light with a cool protective rim.',
    joy: { target: 'security', mechanism: 'Layered shutters make one saved turn feel physically credible.', restraint: 'No literal wall, shield badge, fire, or invulnerability spectacle.' },
    constraints: ['one relay only', 'genuinely transparent background', 'compact readable silhouette'],
    avoid: ['shield symbol', 'flames', 'castle wall', 'text', 'numbers', 'screen', 'scene background'],
    source: 'assets/art-source/parts/firewall.png',
    canvas: { width: 1024, height: 1024 },
    outputs: [{ path: 'public/images/parts/firewall.webp', publicPath: '/images/parts/firewall.webp', width: 512, height: 512, fit: 'contain', format: 'webp', quality: 88, minBytes: 12_000, maxBytes: 180_000, alpha: true }],
    alt: 'A dense steel defensive relay with copper heat fins.',
    generation: fluxGenerated,
    manualChecks: ['transparent corners have zero alpha', 'reads as defensive equipment at 72px', 'contains no shield emblem, fire, or writing'],
  },
  {
    id: 'part-rook-device',
    label: 'Rook identity device',
    family: 'transparent-part',
    status: 'accepted',
    role: 'Closer agent identity',
    brief: 'Give Rook a distinct mechanical identity that communicates decisive pressure.',
    providerDirectives: { flux2Pro: 'ABSOLUTELY BLANK OBJECT SURFACES. OBJECT REQUIREMENT: one squat horizontal hydraulic piston on one plain broad base, with a single amber pressure chamber. No dial, gauge, ruler, scale, panel, screen, tick marks, writing, letters, numbers, symbols, face, limbs, robot body, or weapon.' },
    scene: 'Transparent canvas.',
    subject: 'One compact high-torque lock-driving piston on a broad stable base, with one warm amber pressure chamber.',
    parts: ['rook-device'],
    composition: 'Single centered squat object, complete silhouette, readable from the front at 64px.',
    lighting: 'Neutral studio light with restrained amber reflection.',
    joy: { target: 'competitive recognition', mechanism: 'The poised piston makes Rook feel ready to close the race.', restraint: 'Mechanical device only, never a character body or weapon.' },
    constraints: ['one device only', 'genuinely transparent background', 'broad stable silhouette'],
    avoid: ['face', 'eyes', 'limbs', 'robot body', 'gun', 'text', 'logo', 'scene background'],
    source: 'assets/art-source/parts/rook-device.png',
    canvas: { width: 1024, height: 1024 },
    outputs: [{ path: 'public/images/parts/rook-device.webp', publicPath: '/images/parts/rook-device.webp', width: 384, height: 384, fit: 'contain', format: 'webp', quality: 88, minBytes: 10_000, maxBytes: 150_000, alpha: true }],
    alt: 'Rook’s compact high-torque lock-driving device.',
    generation: fluxGenerated,
    manualChecks: ['transparent corners have zero alpha', 'reads as a forceful device at 64px', 'has no face, limbs, weapon silhouette, or writing'],
  },
  {
    id: 'part-mara-device',
    label: 'Mara identity device',
    family: 'transparent-part',
    status: 'accepted',
    role: 'Scavenger agent identity',
    brief: 'Give Mara a distinct mechanical identity that communicates patient tool collection.',
    scene: 'Transparent canvas.',
    subject: 'One compact rotating tool carousel with nested precision implements and one restrained green find-light.',
    parts: ['mara-device'],
    composition: 'Single centered triangular object, complete silhouette, readable from the front at 64px.',
    lighting: 'Neutral studio light with a restrained green reflection.',
    joy: { target: 'competitive recognition', mechanism: 'Nested tools make Mara’s scavenger behavior visible before reading the copy.', restraint: 'Mechanical device only, never a character body or treasure pile.' },
    constraints: ['one device only', 'genuinely transparent background', 'nested tools remain legible'],
    avoid: ['face', 'eyes', 'limbs', 'robot body', 'treasure', 'text', 'logo', 'scene background'],
    source: 'assets/art-source/parts/mara-device.png',
    canvas: { width: 1024, height: 1024 },
    outputs: [{ path: 'public/images/parts/mara-device.webp', publicPath: '/images/parts/mara-device.webp', width: 384, height: 384, fit: 'contain', format: 'webp', quality: 88, minBytes: 10_000, maxBytes: 150_000, alpha: true }],
    alt: 'Mara’s rotating carousel of precision tools.',
    generation: fluxGenerated,
    manualChecks: ['transparent corners have zero alpha', 'reads as a collecting device at 64px', 'has no face, limbs, treasure, or writing'],
  },
  {
    id: 'part-vesper-device',
    label: 'Vesper identity device',
    family: 'transparent-part',
    status: 'accepted',
    role: 'Disruptor agent identity',
    brief: 'Give Vesper a distinct mechanical identity that communicates targeted interference.',
    providerDirectives: { flux2Pro: 'ABSOLUTELY BLANK OBJECT SURFACES. OBJECT REQUIREMENT: one compact U-shaped cable coupler with exactly two short blunt insulated prongs, a rounded blackened-steel housing, and one restrained red enamel band. It must resemble a cable-routing tool, not a gun, bomb, plug, or weapon. No spark, electric arc, screen, crosshair, text, letters, numbers, symbols, face, eyes, limbs, or robot body.' },
    scene: 'Transparent canvas.',
    subject: 'One compact forked cable-intercept relay with two insulated prongs and one restrained red enamel cut-line.',
    parts: ['vesper-device'],
    composition: 'Single centered forked object, complete silhouette, readable from the front at 64px.',
    lighting: 'Neutral studio light with a restrained red reflection.',
    joy: { target: 'competitive recognition', mechanism: 'The forked relay makes Vesper’s targeted disruption immediately legible.', restraint: 'Mischievous machinery, not a weapon or violent character.' },
    constraints: ['one device only', 'two prongs only', 'genuinely transparent background'],
    avoid: ['spark', 'electric arc', 'crosshair', 'weapon', 'face', 'eyes', 'limbs', 'text', 'scene background'],
    source: 'assets/art-source/parts/vesper-device.png',
    canvas: { width: 1024, height: 1024 },
    outputs: [{ path: 'public/images/parts/vesper-device.webp', publicPath: '/images/parts/vesper-device.webp', width: 384, height: 384, fit: 'contain', format: 'webp', quality: 88, minBytes: 9_000, maxBytes: 150_000, alpha: true }],
    alt: 'Vesper’s forked cable-intercept relay.',
    generation: fluxGenerated,
    manualChecks: ['transparent corners have zero alpha', 'reads as a disrupting device at 64px', 'has no sparks, face, limbs, weapon silhouette, or writing'],
  },
  {
    id: 'part-breach-seal',
    label: 'Open breach seal',
    family: 'transparent-part',
    status: 'accepted',
    role: 'Reusable victory prop',
    brief: 'Create one opened vault seal that can reward a win without importing an entire scene.',
    providerDirectives: { flux2Pro: 'ABSOLUTELY BLANK OBJECT SURFACES. OBJECT REQUIREMENT: one opened FIVE-SIDED PENTAGONAL mechanical seal, not a circle. Put exactly one broad retracted brass latch at each of the five pentagon corners, for exactly five latches total. No sixth latch, extra clamp, dial, gauge, tick marks, diagrams, coins, treasure, explosion, debris, text, letters, numbers, symbols, logo, screen, or pseudo-text.' },
    scene: 'Transparent canvas.',
    subject: 'One blackened-steel pentagonal vault seal with exactly one retracted brass latch at each of its five corners and controlled warm light through the center seam.',
    parts: ['breach-seal', 'breach-light'],
    composition: 'Single centered five-sided open mechanism, complete silhouette, front three-quarter view, 12 percent transparent padding.',
    lighting: 'Neutral studio key with controlled warm light from within the opening.',
    joy: { target: 'earned release', mechanism: 'The retracted latches make completion tactile and unmistakable.', restraint: 'No loot, confetti, debris, or explosive force.' },
    constraints: ['one seal only', 'five retracted latches', 'genuinely transparent background'],
    avoid: ['coins', 'treasure', 'explosion', 'debris', 'text', 'numbers', 'logo', 'scene background'],
    source: 'assets/art-source/parts/breach-seal.png',
    canvas: { width: 1024, height: 1024 },
    outputs: [{ path: 'public/images/parts/breach-seal.webp', publicPath: '/images/parts/breach-seal.webp', width: 512, height: 512, fit: 'contain', format: 'webp', quality: 88, minBytes: 12_000, maxBytes: 180_000, alpha: true }],
    alt: 'An opened radial vault seal with warm light inside.',
    generation: fluxGenerated,
    manualChecks: ['transparent corners have zero alpha', 'open state reads at 96px', 'shows five latches and no treasure, debris, or writing'],
  },
  inventoryPart({
    id: 'part-torque-driver',
    label: 'Torque Driver',
    part: 'torque-driver',
    role: 'Craftable pressure chassis',
    brief: 'Create a grounded mechanical gadget chassis for persistent Pick-focused workshop builds.',
    subject: 'One low-profile blackened-steel torque driver with a broad aged-brass flywheel and two sturdy feet.',
    joy: { target: 'momentum', mechanism: 'The weighty flywheel makes stored mechanical force feel ready to release.', restraint: 'Useful bench equipment, not a drill, gun, or vehicle part.' },
    directives: 'OBJECT REQUIREMENT: one low-profile torque driver with one broad solid brass flywheel and two sturdy feet. The flywheel face and rim must be completely smooth and plain, with no radial lines, grooves, tick marks, increments, pointer, crank, dial, gauge, panel, or decorative marks.',
  }),
  inventoryPart({
    id: 'part-echo-coil',
    label: 'Echo Coil',
    part: 'echo-coil',
    role: 'Craftable signal chassis',
    brief: 'Create a readable analog gadget chassis for signal-focused workshop builds.',
    subject: 'One paired copper induction coil holding a single smoked-glass resonator with a faint blue reflection.',
    joy: { target: 'insight', mechanism: 'The suspended resonator suggests a signal caught between two precise coils.', restraint: 'Analog instrumentation, not magic, electricity, or a digital display.' },
    directives: 'OBJECT REQUIREMENT: one paired copper induction coil with one suspended dark glass resonator and no electric arcs.',
  }),
  inventoryPart({
    id: 'part-decoy-relay',
    label: 'Decoy Relay',
    part: 'decoy-relay',
    role: 'Craftable disruption chassis',
    brief: 'Create a compact routing gadget for clever defensive workshop builds.',
    subject: 'One branching blackened-steel relay with two blank ceramic routing caps and a restrained red enamel line.',
    joy: { target: 'mischief', mechanism: 'A visible fork in the mechanism suggests pressure being sent down the wrong path.', restraint: 'Clever misdirection without sparks, aggression, or weapon cues.' },
    directives: 'OBJECT REQUIREMENT: one compact Y-shaped routing relay with exactly two blank ceramic caps and one red enamel line. The entire lower collar must be plain, smooth, and unmarked, with no segmented rings, measurement marks, pseudo-text, or numeric-like details.',
  }),
  inventoryPart({
    id: 'part-counterweight',
    label: 'Counterweight',
    part: 'counterweight',
    role: 'Craftable recovery chassis',
    brief: 'Create a balanced comeback gadget for workshop builds that favor trailing players.',
    subject: 'One small aged-brass counterweight suspended on a short blackened-steel rail with a broad base.',
    joy: { target: 'comeback hope', mechanism: 'The balanced mass promises stored assistance when pressure rises.', restraint: 'Industrial mechanism, not a scale, coin, pendulum clock, or treasure.' },
    directives: 'OBJECT REQUIREMENT: one compact counterweight on one short horizontal rail and one broad base.',
  }),
  inventoryPart({
    id: 'part-quickset-clamp',
    label: 'Quickset Clamp',
    part: 'quickset-clamp',
    role: 'Craftable opening chassis',
    brief: 'Create a precise spring-loaded gadget for fast-start workshop builds.',
    subject: 'One compact blackened-steel clamp with exactly two padded brass jaws and one visible coiled spring.',
    joy: { target: 'readiness', mechanism: 'The poised jaws make the first move feel prepared and immediate.', restraint: 'A precision tool, not a trap or weapon.' },
    directives: 'OBJECT REQUIREMENT: one compact clamp with exactly two blunt padded jaws and one coiled tension spring.',
  }),
  inventoryPart({
    id: 'part-cache-siphon',
    label: 'Cache Siphon',
    part: 'cache-siphon',
    role: 'Craftable salvage chassis',
    brief: 'Create a compact collection gadget for workshop builds centered on recovered material.',
    subject: 'One small brass salvage intake with a single dark-glass reservoir and one neatly coiled braided hose.',
    joy: { target: 'discovery', mechanism: 'The visible reservoir makes recovered material feel tangible and useful.', restraint: 'Workshop equipment, not a vacuum, weapon, or treasure container.' },
    directives: 'OBJECT REQUIREMENT: one compact salvage intake with one glass reservoir and one capped braided hose.',
  }),
  inventoryPart({
    id: 'part-route-compass',
    label: 'Route Compass',
    part: 'route-compass',
    role: 'Craftable planning chassis',
    brief: 'Create an analog planning gadget for flexible workshop builds.',
    subject: 'One compact three-way route selector assembly with exactly three broad unmarked brass vanes around one blank dark-glass center.',
    joy: { target: 'foresight', mechanism: 'Three poised vanes imply several routes without pretending to show a map.', restraint: 'Mechanical planning tool, not a magical compass or generated interface.' },
    directives: 'OBJECT REQUIREMENT: exactly THREE broad plain brass vanes total, spaced evenly in a Y shape at 120-degree intervals around one completely blank dark-glass center. Count them: three vanes, never four. This is NOT a navigation compass or measuring dial. Use a smooth solid blackened-steel housing with no extra arms, compass points, letters, cardinal directions, numbers, ticks, marks, scales, increments, pointer, map, gauge, or segmented ring.',
  }),
  inventoryPart({
    id: 'part-brass-cogs',
    label: 'Brass Cogs',
    part: 'brass-cogs',
    role: 'Crafting material',
    brief: 'Create an unmistakable small bundle of reusable mechanical crafting stock.',
    subject: 'One tidy interlocking stack of exactly three thick aged-brass gear blanks with empty center bores.',
    joy: { target: 'tactile collection', mechanism: 'A satisfying nested stack makes basic salvage feel useful.', restraint: 'Raw workshop stock, never currency or treasure.' },
    directives: 'OBJECT REQUIREMENT: exactly three thick interlocking aged-brass gear blanks in one tidy stack.',
  }),
  inventoryPart({
    id: 'part-cipher-glass',
    label: 'Cipher Glass',
    part: 'cipher-glass',
    role: 'Crafting material',
    brief: 'Create a distinctive optical crafting component for signal-oriented blueprints.',
    subject: 'One faceted smoked-green optical glass insert held in a small protective brass cradle.',
    joy: { target: 'curiosity', mechanism: 'Subsurface green light hints at useful information inside the material.', restraint: 'Optical component, not a gemstone, jewel, or magical crystal.' },
    directives: 'OBJECT REQUIREMENT: one smoked-green industrial optical glass insert in one small brass cradle.',
    avoid: ['gemstone', 'jewel', 'magic crystal'],
  }),
  inventoryPart({
    id: 'part-flux-wire',
    label: 'Flux Wire',
    part: 'flux-wire',
    role: 'Crafting material',
    brief: 'Create a clean signal-wire component for modular gadget recipes.',
    subject: 'One neat coil of insulated copper signal wire with exactly two blunt capped ends.',
    joy: { target: 'preparedness', mechanism: 'The tidy coil reads as versatile stock ready for assembly.', restraint: 'Inert material with no spark, current, loose mess, or danger.' },
    directives: 'OBJECT REQUIREMENT: one neat coil of insulated copper wire with exactly two visible blunt capped ends and no sparks.',
  }),
  inventoryPart({
    id: 'part-tungsten-shard',
    label: 'Tungsten Shard',
    part: 'tungsten-shard',
    role: 'Crafting material',
    brief: 'Create a dense structural offcut for higher-grade workshop recipes.',
    subject: 'One machined angular tungsten offcut with thick beveled edges and a matte gunmetal surface.',
    joy: { target: 'material value', mechanism: 'Compact weight and clean machining make the offcut feel rare and useful.', restraint: 'Industrial stock, not a blade, ingot, crystal, or precious object.' },
    directives: 'OBJECT REQUIREMENT: one chunky blunt angular tungsten offcut with thick beveled edges.',
    avoid: ['blade', 'knife', 'gem', 'ingot'],
  }),
  inventoryPart({
    id: 'part-oxide-catalyst',
    label: 'Oxide Catalyst',
    part: 'oxide-catalyst',
    role: 'Crafting material',
    brief: 'Create a protected green catalyst component for specialist workshop recipes.',
    subject: 'One sealed squat glass ampoule of muted green oxide catalyst inside a protective aged-brass cage.',
    joy: { target: 'experimentation', mechanism: 'The protected liquid adds a rare alchemical note to a grounded workshop.', restraint: 'Industrial material, not a potion, medicine, or drink.' },
    directives: 'OBJECT REQUIREMENT: one sealed squat glass ampoule in one brass safety cage, with muted green liquid and no bubbles or glow.',
    avoid: ['potion', 'medicine', 'drink', 'magic glow'],
  }),
  inventoryPart({
    id: 'part-vault-resin',
    label: 'Vault Resin',
    part: 'vault-resin',
    role: 'Crafting material',
    brief: 'Create a durable bonding material canister for reinforced workshop builds.',
    subject: 'One compact sealed black ceramic resin canister with one narrow amber-glass level window.',
    joy: { target: 'resourcefulness', mechanism: 'The sealed canister suggests a scarce material saved for a worthy build.', restraint: 'Unlabeled industrial stock, not a drink, explosive, or fuel can.' },
    directives: 'OBJECT REQUIREMENT: one compact sealed black ceramic canister with one narrow amber-glass window and a blunt cap.',
    avoid: ['drink', 'explosive', 'fuel can'],
  }),
]);
