export const ART_FAMILIES = Object.freeze([
  {
    id: 'vault-atmosphere',
    label: 'Vault atmosphere',
    useCase: 'stylized-concept',
    assetType: 'cinematic game and website atmosphere',
    role: 'Establish the fantasy while leaving interaction and evidence to the interface.',
    composition: 'Strong architectural depth, one central vault anchor, restrained detail at copy edges.',
    mood: 'Tense, inviting, sophisticated, and tactile rather than explosive.',
    constraints: ['no people', 'no fake UI', 'no treasure spectacle'],
  },
  {
    id: 'mode-key-art',
    label: 'Mode key art',
    useCase: 'stylized-concept',
    assetType: 'Player Hub mode-card artwork',
    role: 'Explain the difference between instant agent play and live connected play before copy is read.',
    composition: 'Square master with the focal machinery weighted right and low; reserve the upper-left for HTML copy.',
    mood: 'Approachable pressure with a clear invitation to act.',
    constraints: ['no faces', 'no blockchain iconography', 'no fake controls'],
  },
  {
    id: 'replay-story',
    label: 'Replay story',
    useCase: 'stylized-concept',
    assetType: 'replay gallery narrative poster',
    role: 'Capture one mechanically truthful dramatic beat without pretending the image is match footage.',
    composition: 'Square master, one story beat, readable at card scale, no embedded title.',
    mood: 'Specific, dramatic, and worth retelling.',
    constraints: ['show one cause and one consequence', 'no generic action collage', 'no fake match UI'],
  },
  {
    id: 'social-source',
    label: 'Social source',
    useCase: 'stylized-concept',
    assetType: 'text-free social-card scene master',
    role: 'Provide a cinematic brand field underneath deterministic, accessible typography.',
    composition: 'Landscape master with a calm left field and focal machinery to the right.',
    mood: 'Immediate, premium, and high contrast at feed size.',
    constraints: ['no baked-in text', 'no logos', 'protect the left copy field'],
  },
  {
    id: 'outcome-key-art',
    label: 'Outcome key art',
    useCase: 'stylized-concept',
    assetType: 'game victory and resolution backdrop',
    role: 'Reward a completed match with a specific, mechanically truthful moment of release.',
    composition: 'Square master designed to survive a shallow banner crop, with a calm center field for live result text.',
    mood: 'Earned relief, warm release, and quiet mechanical satisfaction rather than spectacle.',
    constraints: ['no people', 'no treasure or coins', 'no fake interface', 'preserve live-copy legibility'],
  },
  {
    id: 'transparent-part',
    label: 'Transparent art part',
    useCase: 'stylized-concept',
    assetType: 'transparent-background modular game-art cutout',
    role: 'Create reusable props that can be layered into banners, empty states, tutorials, and event art.',
    composition: 'Single centered object, complete silhouette, generous transparent padding, consistent three-quarter view.',
    mood: 'Tactile, collectible, and immediately legible.',
    constraints: ['genuinely transparent background', 'no cast shadow outside the object footprint', 'no scene dressing'],
  },
]);

export const ART_FAMILIES_BY_ID = Object.freeze(Object.fromEntries(ART_FAMILIES.map((family) => [family.id, family])));
