export const ART_PARTS = Object.freeze([
  {
    id: 'vault-monolith',
    category: 'anchor',
    prompt: 'one monumental circular bank-vault mechanism with a strong uninterrupted silhouette',
    truth: 'Use exactly five distinct lock stages only when the stages are individually visible.',
  },
  {
    id: 'five-lock-rack',
    category: 'mechanic',
    prompt: 'exactly five clearly separated lock stages arranged as one readable progression, with no extra lock-like rings',
    truth: 'Exactly five lock stages; never add decorative lock-like modules.',
  },
  {
    id: 'lock-module',
    category: 'mechanic',
    prompt: 'one self-contained radial lock stage with a mechanically plausible central keyway and broad blank metal surfaces',
    truth: 'This is one modular stage, not an entire vault or a cluster of locks.',
  },
  {
    id: 'operator-station',
    category: 'table',
    prompt: 'an empty, grounded operator workbench with tactile unlabeled levers and precision tools',
    truth: 'A station implies one player position without depicting an unverified human player.',
  },
  {
    id: 'mechanical-rival',
    category: 'character',
    prompt: 'an unoccupied tabletop rival console with a distinct instrument silhouette; it is machinery, never a robot body',
    truth: 'The rival reads as an agent-controlled station without a face, head, torso, limbs, hands, or human participant.',
  },
  {
    id: 'pick-tool',
    category: 'action',
    prompt: 'a precision brass lockpick under focused amber task light',
    truth: 'Pick is the direct attempt to crack a lock.',
  },
  {
    id: 'search-kit',
    category: 'action',
    prompt: 'an opened field kit revealing one useful precision tool with a restrained green discovery glint',
    truth: 'Search finds tools; it does not directly crack a lock.',
  },
  {
    id: 'sabotage-cable',
    category: 'action',
    prompt: 'one severed braided cable emitting a restrained red spark and a traceable path toward a rival station',
    truth: 'Sabotage disrupts a rival; avoid indiscriminate destruction.',
  },
  {
    id: 'blueprint-trace',
    category: 'accent',
    prompt: 'fine blueprint-blue circuitry or etched planning lines used as a quiet connective accent',
    truth: 'Blue communicates system guidance or connection, not magic.',
  },
  {
    id: 'breach-light',
    category: 'outcome',
    prompt: 'controlled warm light escaping through a newly opened mechanical seam',
    truth: 'A breach should feel earned and precise rather than explosive.',
  },
  {
    id: 'precision-kit',
    category: 'gadget',
    prompt: 'one compact fitted precision kit with three fine lock tools and a brass tension collar',
    truth: 'The Precision Kit improves a Pick attempt; it is equipment, not a weapon.',
  },
  {
    id: 'signal-scanner',
    category: 'gadget',
    prompt: 'one compact analog signal scanner with a single green glass lens and no display',
    truth: 'The Signal Scanner improves Search; it reveals information rather than opening a lock.',
  },
  {
    id: 'firewall-unit',
    category: 'gadget',
    prompt: 'one dense defensive relay with overlapping steel shutters and oxidized copper heat fins',
    truth: 'The Firewall absorbs one sabotage attempt; it is protective equipment, not a shield emblem.',
  },
  {
    id: 'rook-device',
    category: 'rival',
    prompt: 'one compact high-torque lock-driving piston with a broad stable base and warm amber mechanism',
    truth: 'Rook is the closer agent; show decisive pressure without a face or humanoid body.',
  },
  {
    id: 'mara-device',
    category: 'rival',
    prompt: 'one compact rotating tool carousel with nested precision implements and a restrained green find-light',
    truth: 'Mara is the scavenger agent; show patient tool collection without a face or humanoid body.',
  },
  {
    id: 'vesper-device',
    category: 'rival',
    prompt: 'one compact forked cable-intercept relay with a restrained red cut-line accent',
    truth: 'Vesper is the disruptor agent; show targeted interference without a face or humanoid body.',
  },
  {
    id: 'breach-seal',
    category: 'outcome',
    prompt: 'one opened radial vault seal with retracted latches and controlled warm light through its center seam',
    truth: 'The open seal communicates earned victory without coins, loot, or explosive debris.',
  },
  {
    id: 'torque-driver',
    category: 'gadget',
    prompt: 'one compact low-profile torque driver with a wide brass flywheel and sturdy blackened-steel feet',
    truth: 'A torque driver represents persistent Pick pressure; it is a tool, not a weapon.',
  },
  {
    id: 'echo-coil',
    category: 'gadget',
    prompt: 'one paired induction coil with a suspended glass resonator and restrained blue reflection',
    truth: 'An echo coil represents reading previous table signals, not supernatural magic.',
  },
  {
    id: 'decoy-relay',
    category: 'gadget',
    prompt: 'one compact branching relay with two blank ceramic routing caps and a red enamel diversion line',
    truth: 'A decoy relay redirects pressure; it is not a bomb or weapon.',
  },
  {
    id: 'counterweight',
    category: 'gadget',
    prompt: 'one balanced brass counterweight mechanism on a short steel rail',
    truth: 'A counterweight helps a trailing operator recover; it is not currency or treasure.',
  },
  {
    id: 'quickset-clamp',
    category: 'gadget',
    prompt: 'one compact precision clamp with two padded jaws and a coiled tension spring',
    truth: 'A quickset clamp supports a fast opening attempt; it is a tool, not a trap.',
  },
  {
    id: 'cache-siphon',
    category: 'gadget',
    prompt: 'one small salvage intake with a glass reservoir and braided intake hose',
    truth: 'A cache siphon recovers workshop material; it does not steal real currency.',
  },
  {
    id: 'route-compass',
    category: 'gadget',
    prompt: 'one compact mechanical route compass with three unmarked brass vanes around a dark glass center',
    truth: 'A route compass suggests tactical planning without a generated map or display.',
  },
  {
    id: 'brass-cogs',
    category: 'material',
    prompt: 'one tidy stack of three interlocking aged-brass gear blanks',
    truth: 'Brass cogs are crafting stock, not coins or treasure.',
  },
  {
    id: 'cipher-glass',
    category: 'material',
    prompt: 'one faceted piece of smoked green optical glass held in a small brass cradle',
    truth: 'Cipher glass is a precision optical component, not a gem or currency.',
  },
  {
    id: 'flux-wire',
    category: 'material',
    prompt: 'one neat coil of insulated copper signal wire with two blunt capped ends',
    truth: 'Flux wire is inert crafting stock with no sparks or dangerous exposed current.',
  },
  {
    id: 'tungsten-shard',
    category: 'material',
    prompt: 'one machined angular tungsten offcut with beveled edges and a matte metallic finish',
    truth: 'The shard is an industrial offcut, not a blade, crystal, or precious gem.',
  },
  {
    id: 'oxide-catalyst',
    category: 'material',
    prompt: 'one sealed squat glass ampoule of muted green oxide catalyst inside a protective brass cage',
    truth: 'The catalyst is workshop material, never a potion, medicine, or consumable drink.',
  },
  {
    id: 'vault-resin',
    category: 'material',
    prompt: 'one compact sealed black ceramic resin canister with an amber glass level window',
    truth: 'Vault resin is an industrial bonding material with no hazard symbols or writing.',
  },
  {
    id: 'calm-copy-field',
    category: 'composition',
    prompt: 'a calm, low-detail dark field reserved for live interface copy',
    truth: 'Negative space must remain free of focal props and generated text.',
  },
]);

export const ART_PARTS_BY_ID = Object.freeze(Object.fromEntries(ART_PARTS.map((part) => [part.id, part])));
